[package]
name = "galloc"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
# dlmalloc = { path = "/home/gregory/src/dlmalloc-rs", features = [] }
dlmalloc = { git = "https://github.com/grishasobol/dlmalloc-rs", features = ["global"] }
# dlmalloc = { git = "https://github.com/grishasobol/dlmalloc-rs", features = ["global", "gsobol_check"], branch="gsobol_bug_localization" }
