[package]
name = "galloc"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
dlmalloc = { path = "/home/gregory/src/dlmalloc-rs", features = ["global"] }
